### ISSUE TITLE
Add dependabot integration

### ISSUE THREAD

**Issue by krzysztofreczek** [nhood-org/nhood-examples#3]
# Problem

We need automation to keep all dependencies up to date.

# Solution 

There is a `dependabot` tool already configured for other nhood repositories. Do the same for this one.

**Comment by lukaswajdzik** [comment]
I did not find any special files added to the repository.. Is there any?
I see that dependabot app is installed in nhood github with  scanning enabled for all repositories (not selected). Should it be enough, shouldn't it?

**Comment by krzysztofreczek** [comment]
There is no files required. You just log into this tool https://dependabot.com/ with github account and then select the repository to activate. That's it:)

**Comment by lukaswajdzik** [comment]
Done!
