### ISSUE TITLE
Add checkstyle intergation

### ISSUE THREAD

**Issue by krzysztofreczek** [nhood-org/nhood-examples#4]
# Problem

We need an automation that will check if the code style is coherent.

# Solution

See maven configuration of nhood-parent-bom: https://github.com/nhood-org/nhood-parent-bom/blob/master/pom.xml

```
<plugins>
  <plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-checkstyle-plugin</artifactId>
...
</plugins>
```

**Comment by lukaswajdzik** [comment]
added in 14_ExtractExamplesToSeparateRepository
commit "Checkstyle intergation added"
