### ISSUE TITLE
Add Makefile

### ISSUE THREAD

**Issue by krzysztofreczek** [nhood-org/nhood-examples#5]
# Problem

In other repositories we have Makefiles which cover a bunch of typical actions around the project.

# Solution

See Makefile of another repo: https://github.com/nhood-org/nhood-engine-service/blob/master/Makefile
Few of those steps could be implemented within nhood-examples Makefile.

Use Makefile in CICD

**Comment by lukaswajdzik** [comment]
Committed in 14_ExtractExamplesToSeparateRepository, but only trivial version.
Could you please say more about 'Use Makefile in CICD' ?

**Comment by krzysztofreczek** [comment]
> Could you please say more about 'Use Makefile in CICD' ?

Please I do not use mvn commands in the CICD jobs but make jobs:
https://github.com/nhood-org/nhood-engine-service/blob/master/.circleci/config.yml

For examples: l.31:
```
- run: make build-docker-ci
```
is implemented in Makefile in l.61:
```
.PHONY: build-docker-ci
build-docker-ci:
	...
```
